version: '3.1'

services:
  # Banco de dados MongoDB
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: gocase
    volumes:
      - mongo_data:/data/db

  # Interface Web para MongoDB
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://admin:password@mongo:27017/
      ME_CONFIG_BASICAUTH: false

  # Servidor Redis
  redis:
    container_name: redis
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # API Node.js com TypeScript
  gocase-api:
    build:
      context: .  # Usa o Dockerfile na raiz do projeto
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - redis
    environment:
      NODE_ENV: production
      PORT: 3000
      MONGO_URI: mongodb://admin:password@mongo:27017/gocase
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_URL: redis://redis:6379
    volumes:
      - .:/app

volumes:
  redis_data:
  mongo_data:
